/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;
import datechooser.beans.DateChooserDialog;
import java.util.Calendar;
import Database.DBClass;
import java.awt.event.KeyEvent;
import java.util.Arrays;
/**
 *
 * @author Mohan
 */
public class PatientRecordFrame extends javax.swing.JFrame {
DBClass db;
    /**
     * Creates new form PatientRecordFrame
     */
    public PatientRecordFrame() {
        initComponents();
          db=new DBClass();
        db.connectToDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtMobileNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBirthdate = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSrNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtCreatedDate = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(149, 143, 240));
        setForeground(new java.awt.Color(148, 148, 240));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 51, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel1.setText("Patient Information");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(125, 23, 266, 38);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Patient Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 150, 89, 22);
        getContentPane().add(txtPatientName);
        txtPatientName.setBounds(223, 145, 210, 27);

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("    User Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 190, 89, 22);

        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtUserName);
        txtUserName.setBounds(223, 183, 210, 29);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setText("     Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 220, 89, 22);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("        Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 280, 89, 22);

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 260, 310, 76);

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel6.setText("   Birth Date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 390, 85, 22);

        txtMobileNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMobileNoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMobileNoKeyTyped(evt);
            }
        });
        getContentPane().add(txtMobileNo);
        txtMobileNo.setBounds(223, 349, 211, 30);

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel7.setText("     Mobile No");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 350, 85, 22);
        getContentPane().add(txtBirthdate);
        txtBirthdate.setBounds(223, 388, 115, 30);

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("    Sr Number");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 110, 89, 27);
        getContentPane().add(txtSrNo);
        txtSrNo.setBounds(223, 105, 104, 27);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel9.setText("         Gender");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(90, 430, 85, 16);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/DateImage1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(344, 386, 29, 30);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel10.setText("      Age");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(377, 391, 57, 22);

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAgeKeyTyped(evt);
            }
        });
        getContentPane().add(txtAge);
        txtAge.setBounds(444, 388, 71, 30);

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel11.setText("Blood Group");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(120, 470, 85, 32);

        btnSave.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(231, 572, 65, 25);

        btnCancel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(306, 572, 77, 25);

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel12.setText("Created Date");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(120, 520, 108, 23);
        getContentPane().add(txtCreatedDate);
        txtCreatedDate.setBounds(224, 515, 114, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/DateImage1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(344, 515, 29, 30);

        jRadioButton1.setBackground(new java.awt.Color(149, 134, 236));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Male");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(220, 430, 70, 30);

        jRadioButton2.setBackground(new java.awt.Color(149, 134, 236));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setText("Female");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(300, 430, 80, 30);

        jPasswordField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(223, 220, 210, 31);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "A-", "B+", "B-" ,"AB+" ,"AB-" ,"O+" ,"O-"}));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(220, 470, 100, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/MI (950x636).jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 670, 600);

        setSize(new java.awt.Dimension(695, 657));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        datechooser.beans.DateChooserDialog d=new DateChooserDialog();
        d.showDialog(this);
        Calendar c=d.getSelectedDate();
        String date=c.get(Calendar.YEAR)+"/"+(c.get(Calendar.MONTH)+1)+"/"+c.get(Calendar.DAY_OF_MONTH);
        // Date dt=new Date(c);
        // SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
        // sdf.format(c);
        txtBirthdate.setText(date);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
         if(btnSave.getText().equals("Save")){
           
             String result;
             if(jRadioButton1.isSelected())
                 result="Male";
             else
                 result="Female";
        String blood;
             blood = (String) jComboBox2.getSelectedItem();
        String sql = String.format("insert into PatientRecord (SrNo,PatientName,UserName,Password,Address,MobileNo,BirthDate,Age,Gender,BloodGroup,CreationDate) values ('" + txtSrNo.getText() + "','" + txtPatientName.getText() + "','" + txtUserName.getText() + "','" + Arrays.toString(jPasswordField1.getPassword()) + "','" + txtAddress.getText() + "','" + txtMobileNo.getText() + "','" + txtBirthdate.getText() + "','" +  txtAge.getText() + "','" + result + "','" + blood +"','" +  txtCreatedDate.getText() + "')");
        db.ExecuteCommand(sql,"Record Inserted Succefully");
        }
         else
         {
             
         }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        txtSrNo.setText("");
        txtPatientName.setText("");
        txtUserName.setText("");
        txtAddress.setText("");
        txtMobileNo.setText("");
        txtBirthdate.setText("");
        txtAge.setText("");
        txtCreatedDate.setText("");
        int srno =  db.getName();
       String srNo = "" +  srno;
       txtSrNo.setText(srNo);
        
       PatientRecordFrame patientRecordframe = new PatientRecordFrame();
        //patientRecordframe.setVisible(false);
         patientRecordframe.dispose();  //Remove JFrame 1
    }//GEN-LAST:event_btnCancelActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         datechooser.beans.DateChooserDialog d=new DateChooserDialog();
        d.showDialog(this);
        Calendar c=d.getSelectedDate();
        String date=c.get(Calendar.YEAR)+"/"+(c.get(Calendar.MONTH)+1)+"/"+c.get(Calendar.DAY_OF_MONTH);
        // Date dt=new Date(c);
        // SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
        // sdf.format(c);
        txtCreatedDate.setText(date);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
      int srno =  db.getName();
      String srNo = "" +  srno;
      txtSrNo.setText(srNo);
    }//GEN-LAST:event_formWindowOpened

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void txtMobileNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileNoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileNoKeyPressed

    private void txtMobileNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileNoKeyTyped
        // TODO add your handling code here:
        char vchr = evt.getKeyChar();
        if(txtMobileNo.getText().length()>=10) {  
                evt.consume();
            }
        else if(!(Character.isDigit(vchr))
                || (vchr == KeyEvent.VK_BACK_SPACE)
                || (vchr == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtMobileNoKeyTyped

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void txtAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyTyped
        // TODO add your handling code here:
        char vchr = evt.getKeyChar();
        if(txtAge.getText().length()>=2) {  
            evt.consume();
            }
        else if(!(Character.isDigit(vchr))
                || (vchr == KeyEvent.VK_BACK_SPACE)
                || (vchr == KeyEvent.VK_DELETE)){
            evt.consume();}
    }//GEN-LAST:event_txtAgeKeyTyped

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        // TODO add your handling code here:
        if(jPasswordField1.getText().length()>=12) {  
                 evt.consume();
            }
    }//GEN-LAST:event_jPasswordField1KeyTyped

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientRecordFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PatientRecordFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBirthdate;
    private javax.swing.JTextField txtCreatedDate;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtSrNo;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
