/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

///import Database.DBClass;
import Database.DBClass;
import java.sql.ResultSet;
import datechooser.beans.DateChooserDialog;
import java.awt.event.ItemEvent;
import java.util.Calendar;
import java.awt.event.*;
/**
 *
 * @author Mohan
 */
public class PatientMedicineDetailsFrame extends javax.swing.JFrame {
 DBClass db;
String patientName;

    /**
     * Creates new form PatientMedicineDetailsFrame
     */
    public PatientMedicineDetailsFrame() {
        initComponents();
        db=new DBClass();
        db.connectToDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboPatientName = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtSrNo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtMedicineDate1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txtMedicineDate2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtMedicineDate3 = new javax.swing.JTextField();
        txtMedicineDate4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMedicineName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMedicneName2 = new javax.swing.JTextField();
        txtMedicineName3 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtOtherMedicine = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtMedicineTime1 = new javax.swing.JTextField();
        txtmin1 = new javax.swing.JTextField();
        txtampm1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtMedicineTime2 = new javax.swing.JTextField();
        txtmin2 = new javax.swing.JTextField();
        txtampm2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtMedTime3 = new javax.swing.JTextField();
        txtmin3 = new javax.swing.JTextField();
        txtampm3 = new javax.swing.JTextField();
        SaveButton2 = new javax.swing.JButton();
        CancleButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setForeground(new java.awt.Color(204, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        comboPatientName.setToolTipText("");
        comboPatientName.setAutoscrolls(true);
        comboPatientName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboPatientNameItemStateChanged(evt);
            }
        });
        comboPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPatientNameActionPerformed(evt);
            }
        });
        getContentPane().add(comboPatientName);
        comboPatientName.setBounds(214, 71, 180, 31);

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patient Medicine Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 408, 35);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("         Patient Name:-");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(52, 77, 136, 16);

        jLabel19.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText(" Patient Sr No:-");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(85, 117, 103, 16);

        txtSrNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSrNoActionPerformed(evt);
            }
        });
        getContentPane().add(txtSrNo);
        txtSrNo.setBounds(214, 113, 180, 27);

        jLabel20.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("   Med Date 1&2:-");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(70, 160, 118, 16);

        txtMedicineDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicineDate1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMedicineDate1);
        txtMedicineDate1.setBounds(214, 155, 138, 28);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/DateImage1.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(362, 155, 29, 30);
        getContentPane().add(txtMedicineDate2);
        txtMedicineDate2.setBounds(401, 155, 141, 28);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/DateImage1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(548, 155, 29, 30);

        txtMedicineDate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicineDate3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMedicineDate3);
        txtMedicineDate3.setBounds(214, 197, 140, 28);
        getContentPane().add(txtMedicineDate4);
        txtMedicineDate4.setBounds(399, 198, 141, 28);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/DateImage1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(360, 196, 29, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/DateImage1.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(550, 196, 29, 30);

        jLabel26.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText(" Med Date 3 & 4:-");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(70, 196, 118, 28);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  Medicine Name 1:-");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(56, 250, 132, 16);
        getContentPane().add(txtMedicineName);
        txtMedicineName.setBounds(213, 244, 176, 31);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Medicine Name 2:-");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(56, 295, 128, 24);

        txtMedicneName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicneName2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMedicneName2);
        txtMedicneName2.setBounds(213, 293, 176, 31);
        getContentPane().add(txtMedicineName3);
        txtMedicineName3.setBounds(213, 342, 176, 31);

        jLabel24.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Medicine Name 3:-");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(56, 343, 128, 26);

        jLabel25.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("  Other Medicine :-");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(58, 391, 126, 26);

        txtOtherMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOtherMedicineActionPerformed(evt);
            }
        });
        getContentPane().add(txtOtherMedicine);
        txtOtherMedicine.setBounds(213, 391, 176, 29);

        jLabel21.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Medicine Time 1:-");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(66, 440, 118, 21);

        txtMedicineTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicineTime1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMedicineTime1);
        txtMedicineTime1.setBounds(213, 438, 54, 26);

        txtmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmin1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtmin1);
        txtmin1.setBounds(273, 438, 50, 26);

        txtampm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtampm1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtampm1);
        txtampm1.setBounds(329, 438, 60, 26);

        jLabel22.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Medicine Time 2:-");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(66, 485, 118, 21);

        txtMedicineTime2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedicineTime2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMedicineTime2);
        txtMedicineTime2.setBounds(213, 482, 50, 29);

        txtmin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmin2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtmin2);
        txtmin2.setBounds(272, 483, 52, 26);

        txtampm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtampm2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtampm2);
        txtampm2.setBounds(330, 483, 57, 26);

        jLabel23.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Medicine Time 3:-");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(66, 529, 118, 42);
        getContentPane().add(txtMedTime3);
        txtMedTime3.setBounds(213, 529, 49, 27);

        txtmin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmin3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtmin3);
        txtmin3.setBounds(272, 529, 53, 26);

        txtampm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtampm3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtampm3);
        txtampm3.setBounds(335, 529, 52, 26);

        SaveButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        SaveButton2.setText("Save");
        SaveButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(SaveButton2);
        SaveButton2.setBounds(213, 604, 65, 25);

        CancleButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        CancleButton2.setText("Cancle");
        CancleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(CancleButton2);
        CancleButton2.setBounds(284, 604, 77, 25);

        jLabel3.setBackground(new java.awt.Color(204, 255, 255));
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Database/MI@ (950x633).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-10, 0, 870, 630);

        setSize(new java.awt.Dimension(656, 672));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     class ItemChangeListener implements ItemListener{
    @Override
    public void itemStateChanged(ItemEvent event) {
      // if (event.getStateChange() == ItemEvent.SELECTED) {
        try {
             String patientName= comboPatientName.getSelectedItem().toString();
             int ix=patientName.indexOf("-");
             String SrNO = "" + ix;
             patientName=patientName.substring(0,ix);
             patientName=patientName.trim();
             txtSrNo.setText(SrNO);
        } catch (Exception e) {
            e.getMessage();
           //  JOptionPane.showMessageDialog(null, "I am happy.");
        }
       }    
}
    
    private void comboPatientNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboPatientNameItemStateChanged
        // TODO add your handling code here:
        try {
            String patientName= comboPatientName.getSelectedItem().toString();
            int ix=patientName.indexOf("-");
            String SrNO = "" + ix;
            patientName=patientName.substring(0,ix);
            patientName=patientName.trim();
            txtSrNo.setText(SrNO);
        } catch (Exception e) {
            e.getMessage();
            //  JOptionPane.showMessageDialog(null, "I am happy.");
        }
    }//GEN-LAST:event_comboPatientNameItemStateChanged

    private void comboPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPatientNameActionPerformed
        // TODO add your handling code here:
          try {
            String patientName= comboPatientName.getSelectedItem().toString();
            String[] result = patientName.split("-");
            int ix=patientName.indexOf("-");
            String SrNO = "" + result[0];
            patientName=patientName.substring(0,ix);
            patientName=patientName.trim();
            txtSrNo.setText(SrNO);
        } catch (Exception e) {
            e.getMessage();
            //  JOptionPane.showMessageDialog(null, "I am happy.");
        }
    }//GEN-LAST:event_comboPatientNameActionPerformed

    private void txtSrNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSrNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSrNoActionPerformed

    private void txtMedicineDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicineDate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicineDate1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        datechooser.beans.DateChooserDialog d=new DateChooserDialog();
        d.showDialog(this);
        Calendar c=d.getSelectedDate();
        String date=c.get(Calendar.YEAR)+"/"+(c.get(Calendar.MONTH)+1)+"/"+c.get(Calendar.DAY_OF_MONTH);
        txtMedicineDate1.setText(date);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        datechooser.beans.DateChooserDialog d=new DateChooserDialog();
        d.showDialog(this);
        Calendar c=d.getSelectedDate();
        String date=c.get(Calendar.YEAR)+"/"+(c.get(Calendar.MONTH)+1)+"/"+c.get(Calendar.DAY_OF_MONTH);
        // Date dt=new Date(c);
        // SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
        // sdf.format(c);
        txtMedicineDate2.setText(date);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtMedicineDate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicineDate3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicineDate3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        datechooser.beans.DateChooserDialog d=new DateChooserDialog();
        d.showDialog(this);
        Calendar c=d.getSelectedDate();
        String date=c.get(Calendar.YEAR)+"/"+(c.get(Calendar.MONTH)+1)+"/"+c.get(Calendar.DAY_OF_MONTH);
        txtMedicineDate3.setText(date);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        datechooser.beans.DateChooserDialog d=new DateChooserDialog();
        d.showDialog(this);
        Calendar c=d.getSelectedDate();
        String date=c.get(Calendar.YEAR)+"/"+(c.get(Calendar.MONTH)+1)+"/"+c.get(Calendar.DAY_OF_MONTH);
        txtMedicineDate4.setText(date);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtMedicneName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicneName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicneName2ActionPerformed

    private void txtOtherMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOtherMedicineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOtherMedicineActionPerformed

    private void txtMedicineTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicineTime1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicineTime1ActionPerformed

    private void txtmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmin1ActionPerformed

    private void txtampm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtampm1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtampm1ActionPerformed

    private void txtMedicineTime2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedicineTime2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedicineTime2ActionPerformed

    private void txtmin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmin2ActionPerformed

    private void txtampm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtampm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtampm2ActionPerformed

    private void txtmin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmin3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmin3ActionPerformed

    private void txtampm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtampm3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtampm3ActionPerformed

    private void SaveButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButton2ActionPerformed

        try {
            GetPatientName();
            //
            if(SaveButton2.getText().equals("Save")){
                String sql = null;
                if(!txtMedicineDate1.getText().equals(""))
                {
                    String sql1 = String.format("insert into PatientMedicineDetails (PatientName,SrNo,MedicineDate,MedicineName1,MedicineName2,MedicineName3,OtherMedicine,MedicineTime1,MedicineMin1,MT1,MedicineTime2,MedicineMin2,MT2,MedicineTime3,MedicineMin3,MT3) values ('" + patientName + "','" +
                        txtSrNo.getText() + "','" + txtMedicineDate1.getText()  + "','" + txtMedicineName.getText() + "','"  + txtMedicneName2.getText()+ "','" + txtMedicineName3.getText() + "','"  + txtOtherMedicine.getText() + "','"
                        + txtMedicineTime1.getText() + "','" + txtmin1.getText() + "','" + txtampm1.getText() + "','" + txtMedicineTime2.getText() + "','" + txtmin2.getText() + "','"  + txtampm2.getText() + "','"
                        + txtMedTime3.getText() + "','" + txtmin3.getText()  + "','" + txtampm3.getText() + "')");
                    db.ExecuteCommand(sql1,"Record Inserted Succefully");
                }
                if(!txtMedicineDate2.getText().equals(""))
                {
                    String sql2= String.format("insert into PatientMedicineDetails (PatientName,SrNo,MedicineDate,MedicineName1,MedicineName2,MedicineName3,OtherMedicine,MedicineTime1,MedicineMin1,MT1,MedicineTime2,MedicineMin2,MT2,MedicineTime3,MedicineMin3,MT3) values ('" + patientName + "','" +
                        txtSrNo.getText() + "','" + txtMedicineDate2.getText()  + "','" + txtMedicineName.getText() + "','"  + txtMedicneName2.getText()+ "','" + txtMedicineName3.getText() + "','"  + txtOtherMedicine.getText() + "','"
                        + txtMedicineTime1.getText() + "','" + txtmin1.getText() + "','" + txtampm1.getText() + "','" + txtMedicineTime2.getText() + "','" + txtmin2.getText() + "','"  + txtampm2.getText() + "','"
                        + txtMedTime3.getText() + "','" + txtmin3.getText()  + "','" + txtampm3.getText() + "')");
                    db.ExecuteCommand(sql2,"Record Inserted Succefully");
                }
                if(!txtMedicineDate3.getText().equals(""))
                {
                    String sql3 = String.format("insert into PatientMedicineDetails (PatientName,SrNo,MedicineDate,MedicineName1,MedicineName2,MedicineName3,OtherMedicine,MedicineTime1,MedicineMin1,MT1,MedicineTime2,MedicineMin2,MT2,MedicineTime3,MedicineMin3,MT3) values ('" + patientName + "','" +
                        txtSrNo.getText() + "','" + txtMedicineDate3.getText()  + "','" + txtMedicineName.getText() + "','"  + txtMedicneName2.getText()+ "','" + txtMedicineName3.getText() + "','"  + txtOtherMedicine.getText() + "','"
                        + txtMedicineTime1.getText() + "','" + txtmin1.getText() + "','" + txtampm1.getText() + "','" + txtMedicineTime2.getText() + "','" + txtmin2.getText() + "','"  + txtampm2.getText() + "','"
                        + txtMedTime3.getText() + "','" + txtmin3.getText()  + "','" + txtampm3.getText() + "')");
                    db.ExecuteCommand(sql3,"Record Inserted Succefully");
                }
                if(!txtMedicineDate4.getText().equals(""))
                {
                    String sql4 = String.format("insert into PatientMedicineDetails (PatientName,SrNo,MedicineDate,MedicineName1,MedicineName2,MedicineName3,OtherMedicine,MedicineTime1,MedicineMin1,MT1,MedicineTime2,MedicineMin2,MT2,MedicineTime3,MedicineMin3,MT3) values ('" + patientName + "','" +
                        txtSrNo.getText() + "','" + txtMedicineDate4.getText()  + "','" + txtMedicineName.getText() + "','"  + txtMedicneName2.getText()+ "','" + txtMedicineName3.getText() + "','"  + txtOtherMedicine.getText() + "','"
                        + txtMedicineTime1.getText() + "','" + txtmin1.getText() + "','" + txtampm1.getText() + "','" + txtMedicineTime2.getText() + "','" + txtmin2.getText() + "','"  + txtampm2.getText() + "','"
                        + txtMedTime3.getText() + "','" + txtmin3.getText()  + "','" + txtampm3.getText() + "')");
                    db.ExecuteCommand(sql4,"Record Inserted Succefully");
                }
                //String sql=String.format("Insert into PatientMedicineDetails values('%s',%s,'%s','%s','%s','%s','%s')",patientName,txtSrNo.getText(),txtMedicineName.getText(),txtMedicineDate.getText(),txtMedicineTime1.getText(),txtMedicineTime2.getText(),txtMedTime3.getText());
                //db.ExecuteCommand(sql4,"Record Inserted Succefully");

            }
            //        else{//EndrollmentNo,studentName,deptId,dep_name,address,MobileNo
                //
                //            //String sql=String.format("Update PatinetMedicineDetails set MedicineTime1='%s',MedicineTime2='%s',MedicineTime3='%s' where SrNo=%s",txtSrNo.getText(),,addressTextField.getText(),MobileNoTextBox.getText(),EndrollmentnoTextBox.getText());
                //             String sql=String.format("Update PatinetMedicineDetails set MedicineTime1='"+txtMedicineTime1.getText()+"',MedicineTime2="+txtMedicineTime2.getText()+",MedicineTime3='"+txtMedTime3.getText()+"' where PatientName="+patientName + "and MedicineDate="+txtMedicineDate.getText() );
                //            db.ExecuteCommand(sql,"Record Updated Succefully");
                //        }
            //        db.fillTable(Tab1,"select MedicineName,MedicineDate,MedicineTime1,MedicineTime2,MedicineTime3 from PatientMedicineDetails");
            //        // TODO add your handling code here:
            //        CancleButton.doClick();
        }
        catch(Exception e)
        {
            e.getMessage();
        }
    }//GEN-LAST:event_SaveButton2ActionPerformed

    private void CancleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancleButton2ActionPerformed
        // TODO add your handling code here:
        //        EndrollmentnoTextBox.setText("");
        txtMedicineName.setText("");
        txtMedicneName2.setText("");
        txtMedicineName3.setText("");
        txtOtherMedicine.setText("");
        txtMedicineTime1.setText("");
        txtMedicineDate1.setText("");
        txtMedicineDate2.setText("");
        txtMedicineDate3.setText("");
        txtMedicineDate4.setText("");
        txtmin1.setText("");
        txtampm1.setText("");
        txtMedicineTime2.setText("");
        txtmin2.setText("");
        txtampm1.setText("");
        txtMedTime3.setText("");
        txtmin3.setText("");
        txtampm3.setText("");
        SaveButton2.setText("Save");
        // MedicineName1.set
    }//GEN-LAST:event_CancleButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         db.fillCombo(comboPatientName,"select Concat(SrNo,'-',PatientName) as PatientName from PatientRecord");
        comboPatientName.addItemListener(new ItemChangeListener());
    }//GEN-LAST:event_formWindowOpened

     void GetPatientName (){
       patientName = comboPatientName.getSelectedItem().toString();
             int ix=patientName.indexOf("-");
             String SrNO = "" + ix;
             //patientName=patientName.substring(0,0);
             //patientName=patientName.trim();
             txtSrNo.setText(SrNO);
             
             String[] parts = patientName.split("-");
             String part1 = parts[0]; // 004
             patientName = parts[1];        
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientMedicineDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientMedicineDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientMedicineDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientMedicineDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientMedicineDetailsFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancleButton2;
    private javax.swing.JButton SaveButton2;
    private javax.swing.JComboBox comboPatientName;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtMedTime3;
    private javax.swing.JTextField txtMedicineDate1;
    private javax.swing.JTextField txtMedicineDate2;
    private javax.swing.JTextField txtMedicineDate3;
    private javax.swing.JTextField txtMedicineDate4;
    private javax.swing.JTextField txtMedicineName;
    private javax.swing.JTextField txtMedicineName3;
    private javax.swing.JTextField txtMedicineTime1;
    private javax.swing.JTextField txtMedicineTime2;
    private javax.swing.JTextField txtMedicneName2;
    private javax.swing.JTextField txtOtherMedicine;
    private javax.swing.JTextField txtSrNo;
    private javax.swing.JTextField txtampm1;
    private javax.swing.JTextField txtampm2;
    private javax.swing.JTextField txtampm3;
    private javax.swing.JTextField txtmin1;
    private javax.swing.JTextField txtmin2;
    private javax.swing.JTextField txtmin3;
    // End of variables declaration//GEN-END:variables
}
